language: java
jdk: oraclejdk7
before_install:
  - wget https://github.com/n1k0/casperjs/archive/1.1-beta3.tar.gz
  - tar xvf ${CASPER_VERSION}.tar.gz -C casper
  - export PATH=$PATH:casper/bin
before_script:
  - phantomjs --version
  - casperjs --version
script:
  - mvn install
  - mvn -Pit install